"""Discovery artifact contracts and helpers."""

from importlib import import_module

from .grc9_manifest import (
    GRC9_DISCOVERY_FAMILY,
    GRC9_DISCOVERY_PROGRAM,
    GRC9_DISCOVERY_TRACK,
    GRC9_PHENOMENOLOGY_DISCOVERY_MANIFEST_VERSION,
    GRC9DiscoveryManifest,
    GRC9EvidenceFields,
    GRC9ManifestRunScope,
    GRC9MotifRecord,
    GRC9PredictedSignature,
    GRC9ReviewHistoryEntry,
    GRC9SelectorSpec,
    GRC9SourceArtifact,
    GRC9SourceReference,
    GRC9StructureHypothesis,
    generated_lane_name,
    is_discovery_profile_name,
    is_generated_lane_name,
    is_session_id,
    perturbation_lane_name,
    profile_name,
)
from .grc9_mechanism_ledger import (
    GRC9_MECHANISM_LEDGER_VERSION,
    GRC9MechanismLedger,
    GRC9MechanismLedgerEntry,
    RUNTIME_DEFERRED,
    RUNTIME_OUT_OF_SCOPE,
    RUNTIME_RESERVED_FUTURE,
    RUNTIME_TESTABLE,
    default_grc9_mechanism_ledger,
    hypothesis_runtime_status_matches_ledger,
)
from .grc9v3_mechanism_ledger import (
    GRC9V3_MECHANISM_LEDGER_VERSION,
    GRC9V3_RUNTIME_CAPABILITY_GATED,
    GRC9V3_RUNTIME_DEFERRED,
    GRC9V3_RUNTIME_OUT_OF_SCOPE,
    GRC9V3_RUNTIME_TESTABLE,
    GRC9V3MechanismLedger,
    GRC9V3MechanismLedgerEntry,
    GRC9V3PredictedSignature,
    GRC9V3SourceReference,
    default_grc9v3_mechanism_ledger,
    hypothesis_runtime_status_matches_grc9v3_ledger,
)
from .grc9_hypothesis_catalog import (
    GRC9_HYPOTHESIS_CATALOG_VERSION,
    GRC9HypothesisCatalog,
    GRC9PerturbationSpec,
    GRC9SeedControlSpec,
    GRC9SeedFamilySpec,
    default_grc9_hypothesis_catalog,
)
from .grc9v3_hypothesis_catalog import (
    GRC9V3_HYPOTHESIS_CATALOG_VERSION,
    GRC9V3HypothesisCatalog,
    GRC9V3PerturbationSpec,
    GRC9V3SeedControlSpec,
    GRC9V3SeedFamilySpec,
    default_grc9v3_hypothesis_catalog,
    grc9v3_profile_name,
    is_grc9v3_discovery_profile_name,
)
from .grc9_seed_generator import (
    GRC9_COMPLEX_EVENT_STABILITY_NAMES,
    GRC9_COMPLEX_EVENT_STABILITY_PROFILE,
    GRC9_CORRECTED_GROWTH_COMBO_NAMES,
    GRC9_CORRECTED_GROWTH_COMBO_PROFILE,
    GRC9_CORRECTED_GROWTH_COMPLEX_NAMES,
    GRC9_CORRECTED_GROWTH_COMPLEX_PROFILE,
    GRC9_CORRECTED_GROWTH_ELEMENTARY_NAMES,
    GRC9_CORRECTED_GROWTH_ELEMENTARY_PROFILE,
    GRC9_LIFECYCLE_COMBO_NAMES,
    GRC9_LIFECYCLE_COMBO_PROFILE,
    GRC9_LIFECYCLE_EMITTER_NAMES,
    GRC9_LIFECYCLE_EMITTER_PERTURBATION_NAMES,
    GRC9_LIFECYCLE_EMITTER_REPAIR_PROFILE,
    GRC9_SEED_GENERATOR_VERSION,
    GRC9_TARGETED_DIAGNOSTIC_NAMES,
    GRC9_TARGETED_DIAGNOSTIC_PROFILE,
    GRC9GeneratedSeed,
    generate_grc9_complex_event_stability_fixture,
    generate_grc9_corrected_growth_combo_fixture,
    generate_grc9_corrected_growth_complex_fixture,
    generate_grc9_corrected_growth_elementary_fixture,
    generate_grc9_lifecycle_combo,
    generate_grc9_lifecycle_emitter,
    generate_grc9_lifecycle_emitter_perturbation,
    generate_grc9_seed,
    generate_grc9_seed_perturbation,
    generate_grc9_targeted_diagnostic_fixture,
)
from .grc9v3_seed_generator import (
    GRC9V3_COMPLEX_HYBRID_NAMES,
    GRC9V3_COMPLEX_HYBRID_PROFILE,
    GRC9V3_PRESSURE_BOUNDARY_NAMES,
    GRC9V3_PRESSURE_BOUNDARY_PROFILE,
    GRC9V3_SEED_GENERATOR_VERSION,
    GRC9V3GeneratedSeed,
    generate_grc9v3_complex_hybrid_example,
    generate_grc9v3_pressure_boundary_example,
    generate_grc9v3_seed,
    generate_grc9v3_seed_perturbation,
)

__all__ = [
    "GRC9_DISCOVERY_FAMILY",
    "GRC9_DISCOVERY_PROGRAM",
    "GRC9_DISCOVERY_TRACK",
    "GRC9_PHENOMENOLOGY_DISCOVERY_MANIFEST_VERSION",
    "GRC9_MECHANISM_LEDGER_VERSION",
    "GRC9V3_MECHANISM_LEDGER_VERSION",
    "GRC9_HYPOTHESIS_CATALOG_VERSION",
    "GRC9V3_HYPOTHESIS_CATALOG_VERSION",
    "GRC9_SEED_GENERATOR_VERSION",
    "GRC9V3_SEED_GENERATOR_VERSION",
    "GRC9V3_DISCOVERY_LOW_STEP_COUNTS",
    "GRC9V3_SELECTOR_VALIDATION_VERSION",
    "GRC9V3_VISUAL_REVIEW_VERSION",
    "GRC9V3_HESSIAN_COMPARATOR_REVIEW_VERSION",
    "GRC9V3_REVIEWED_MOTIF_CATALOG_VERSION",
    "GRC9V3_CATALOG_BREADTH_EXPANSION_VERSION",
    "GRC9V3_SOURCE_HANDOFF_VERSION",
    "GRC9V3_COMPLEX_HYBRID_NAMES",
    "GRC9V3_COMPLEX_HYBRID_PROFILE",
    "GRC9V3_PRESSURE_BOUNDARY_NAMES",
    "GRC9V3_PRESSURE_BOUNDARY_PROFILE",
    "GRC9_CHECKPOINT_VISUAL_INDEX_VERSION",
    "GRC9_GRCL9_HANDOFF_VERSION",
    "GRC9_REVIEWED_MOTIF_CATALOG_VERSION",
    "GRC9_SELECTOR_FEEDBACK_VERSION",
    "GRC9_COMPLEX_EVENT_STABILITY_NAMES",
    "GRC9_COMPLEX_EVENT_STABILITY_PROFILE",
    "GRC9_CORRECTED_GROWTH_COMBO_NAMES",
    "GRC9_CORRECTED_GROWTH_COMBO_PROFILE",
    "GRC9_CORRECTED_GROWTH_COMPLEX_NAMES",
    "GRC9_CORRECTED_GROWTH_COMPLEX_PROFILE",
    "GRC9_CORRECTED_GROWTH_CATALOG_VERSION",
    "GRC9_CORRECTED_GROWTH_ELEMENTARY_NAMES",
    "GRC9_CORRECTED_GROWTH_ELEMENTARY_PROFILE",
    "GRC9_LIFECYCLE_COMBO_NAMES",
    "GRC9_LIFECYCLE_COMBO_PROFILE",
    "GRC9_LIFECYCLE_EMITTER_NAMES",
    "GRC9_LIFECYCLE_EMITTER_PERTURBATION_NAMES",
    "GRC9_LIFECYCLE_EMITTER_REPAIR_PROFILE",
    "GRC9_TARGETED_DIAGNOSTIC_NAMES",
    "GRC9_TARGETED_DIAGNOSTIC_PROFILE",
    "GRC9DiscoveryManifest",
    "GRC9EvidenceFields",
    "GRC9CheckpointLink",
    "GRC9CheckpointVisualIndexSession",
    "GRC9GeneratedSeed",
    "GRC9V3GeneratedSeed",
    "GRC9V3DiscoveryLaneRun",
    "GRC9V3DiscoverySessionRun",
    "GRC9V3LaneSelectorValidation",
    "GRC9V3SelectorDefinition",
    "GRC9V3SelectorResult",
    "GRC9V3SelectorValidationSession",
    "GRC9V3CheckpointLink",
    "GRC9V3HessianComparatorReviewSession",
    "GRC9V3HessianLaneReview",
    "GRC9V3HessianPairReview",
    "GRC9V3ReviewHistoryEntry",
    "GRC9V3ReviewedMotifCatalogSession",
    "GRC9V3ReviewedMotifRecord",
    "GRC9V3CatalogBreadthExpansionSession",
    "GRC9V3SourceHandoffSession",
    "GRC9V3MotifVisualRecord",
    "GRC9V3SkippedVisualRecord",
    "GRC9V3VisualReviewSession",
    "GRC9GRCL9HandoffSession",
    "GRC9CorrectedGrowthCatalogSession",
    "GRC9ManifestRunScope",
    "GRC9MechanismLedger",
    "GRC9MechanismLedgerEntry",
    "GRC9V3MechanismLedger",
    "GRC9V3MechanismLedgerEntry",
    "GRC9V3PredictedSignature",
    "GRC9V3SourceReference",
    "GRC9MotifRecord",
    "GRC9PredictedSignature",
    "GRC9ReviewHistoryEntry",
    "GRC9ReviewedMotifCatalogSession",
    "GRC9SelectorSpec",
    "GRC9HypothesisCatalog",
    "GRC9V3HypothesisCatalog",
    "GRC9V3PerturbationSpec",
    "GRC9V3SeedControlSpec",
    "GRC9V3SeedFamilySpec",
    "GRC9PerturbationSpec",
    "GRC9SeedControlSpec",
    "GRC9SeedFamilySpec",
    "GRC9SourceArtifact",
    "GRC9SourceReference",
    "GRC9StructureHypothesis",
    "GRC9MotifCheckpointVisualRecord",
    "GRC9SelectorFeedbackItem",
    "GRC9SelectorFeedbackSession",
    "GRC9SkippedMotifRecord",
    "RUNTIME_DEFERRED",
    "RUNTIME_OUT_OF_SCOPE",
    "RUNTIME_RESERVED_FUTURE",
    "RUNTIME_TESTABLE",
    "GRC9V3_RUNTIME_CAPABILITY_GATED",
    "GRC9V3_RUNTIME_DEFERRED",
    "GRC9V3_RUNTIME_OUT_OF_SCOPE",
    "GRC9V3_RUNTIME_TESTABLE",
    "GRC9V3_COMPLEX_HYBRID_STEP_COUNTS",
    "GRC9V3_PRESSURE_BOUNDARY_STEP_COUNTS",
    "default_grc9_hypothesis_catalog",
    "default_grc9v3_hypothesis_catalog",
    "default_grc9_mechanism_ledger",
    "default_grc9v3_mechanism_ledger",
    "generated_lane_name",
    "grc9v3_profile_name",
    "generate_grc9_complex_event_stability_fixture",
    "generate_grc9_corrected_growth_combo_fixture",
    "generate_grc9_corrected_growth_complex_fixture",
    "generate_grc9_corrected_growth_elementary_fixture",
    "generate_grc9_lifecycle_combo",
    "generate_grc9_lifecycle_emitter",
    "generate_grc9_lifecycle_emitter_perturbation",
    "generate_grc9_seed",
    "generate_grc9_seed_perturbation",
    "generate_grc9_targeted_diagnostic_fixture",
    "generate_grc9v3_seed",
    "generate_grc9v3_complex_hybrid_example",
    "generate_grc9v3_pressure_boundary_example",
    "generate_grc9v3_seed_perturbation",
    "hypothesis_runtime_status_matches_ledger",
    "hypothesis_runtime_status_matches_grc9v3_ledger",
    "is_discovery_profile_name",
    "is_grc9v3_discovery_profile_name",
    "is_generated_lane_name",
    "is_session_id",
    "perturbation_lane_name",
    "profile_name",
    "run_grc9_checkpoint_visual_index",
    "run_grc9_corrected_growth_catalog",
    "run_grc9_grcl9_handoff",
    "run_grc9_reviewed_motif_catalog",
    "run_grc9_selector_feedback",
    "run_grc9v3_discovery_control_session",
    "run_grc9v3_complex_hybrid_session",
    "run_grc9v3_pressure_boundary_session",
    "run_grc9v3_selector_validation",
    "run_grc9v3_visual_review",
    "run_grc9v3_hessian_comparator_review",
    "run_grc9v3_reviewed_motif_catalog",
    "run_grc9v3_catalog_breadth_expansion",
    "run_grc9v3_source_handoff",
]

_LAZY_EXPORTS = {
    "GRC9_CHECKPOINT_VISUAL_INDEX_VERSION": (
        ".grc9_checkpoint_visual_index",
        "GRC9_CHECKPOINT_VISUAL_INDEX_VERSION",
    ),
    "GRC9CheckpointLink": (".grc9_checkpoint_visual_index", "GRC9CheckpointLink"),
    "GRC9CheckpointVisualIndexSession": (
        ".grc9_checkpoint_visual_index",
        "GRC9CheckpointVisualIndexSession",
    ),
    "GRC9MotifCheckpointVisualRecord": (
        ".grc9_checkpoint_visual_index",
        "GRC9MotifCheckpointVisualRecord",
    ),
    "GRC9SkippedMotifRecord": (
        ".grc9_checkpoint_visual_index",
        "GRC9SkippedMotifRecord",
    ),
    "run_grc9_checkpoint_visual_index": (
        ".grc9_checkpoint_visual_index",
        "run_grc9_checkpoint_visual_index",
    ),
    "GRC9_GRCL9_HANDOFF_VERSION": (
        ".grc9_grcl9_handoff",
        "GRC9_GRCL9_HANDOFF_VERSION",
    ),
    "GRC9GRCL9HandoffSession": (
        ".grc9_grcl9_handoff",
        "GRC9GRCL9HandoffSession",
    ),
    "run_grc9_grcl9_handoff": (
        ".grc9_grcl9_handoff",
        "run_grc9_grcl9_handoff",
    ),
    "GRC9_REVIEWED_MOTIF_CATALOG_VERSION": (
        ".grc9_reviewed_motif_catalog",
        "GRC9_REVIEWED_MOTIF_CATALOG_VERSION",
    ),
    "GRC9ReviewedMotifCatalogSession": (
        ".grc9_reviewed_motif_catalog",
        "GRC9ReviewedMotifCatalogSession",
    ),
    "run_grc9_reviewed_motif_catalog": (
        ".grc9_reviewed_motif_catalog",
        "run_grc9_reviewed_motif_catalog",
    ),
    "GRC9_CORRECTED_GROWTH_CATALOG_VERSION": (
        ".grc9_corrected_growth_catalog",
        "GRC9_CORRECTED_GROWTH_CATALOG_VERSION",
    ),
    "GRC9CorrectedGrowthCatalogSession": (
        ".grc9_corrected_growth_catalog",
        "GRC9CorrectedGrowthCatalogSession",
    ),
    "run_grc9_corrected_growth_catalog": (
        ".grc9_corrected_growth_catalog",
        "run_grc9_corrected_growth_catalog",
    ),
    "GRC9_SELECTOR_FEEDBACK_VERSION": (
        ".grc9_selector_feedback",
        "GRC9_SELECTOR_FEEDBACK_VERSION",
    ),
    "GRC9SelectorFeedbackItem": (
        ".grc9_selector_feedback",
        "GRC9SelectorFeedbackItem",
    ),
    "GRC9SelectorFeedbackSession": (
        ".grc9_selector_feedback",
        "GRC9SelectorFeedbackSession",
    ),
    "run_grc9_selector_feedback": (
        ".grc9_selector_feedback",
        "run_grc9_selector_feedback",
    ),
    "GRC9V3_DISCOVERY_LOW_STEP_COUNTS": (
        ".grc9v3_discovery_runner",
        "GRC9V3_DISCOVERY_LOW_STEP_COUNTS",
    ),
    "GRC9V3DiscoveryLaneRun": (
        ".grc9v3_discovery_runner",
        "GRC9V3DiscoveryLaneRun",
    ),
    "GRC9V3DiscoverySessionRun": (
        ".grc9v3_discovery_runner",
        "GRC9V3DiscoverySessionRun",
    ),
    "GRC9V3_COMPLEX_HYBRID_STEP_COUNTS": (
        ".grc9v3_discovery_runner",
        "GRC9V3_COMPLEX_HYBRID_STEP_COUNTS",
    ),
    "GRC9V3_PRESSURE_BOUNDARY_STEP_COUNTS": (
        ".grc9v3_discovery_runner",
        "GRC9V3_PRESSURE_BOUNDARY_STEP_COUNTS",
    ),
    "run_grc9v3_discovery_control_session": (
        ".grc9v3_discovery_runner",
        "run_grc9v3_discovery_control_session",
    ),
    "run_grc9v3_complex_hybrid_session": (
        ".grc9v3_discovery_runner",
        "run_grc9v3_complex_hybrid_session",
    ),
    "run_grc9v3_pressure_boundary_session": (
        ".grc9v3_discovery_runner",
        "run_grc9v3_pressure_boundary_session",
    ),
    "GRC9V3_SELECTOR_VALIDATION_VERSION": (
        ".grc9v3_selector_validation",
        "GRC9V3_SELECTOR_VALIDATION_VERSION",
    ),
    "GRC9V3LaneSelectorValidation": (
        ".grc9v3_selector_validation",
        "GRC9V3LaneSelectorValidation",
    ),
    "GRC9V3SelectorDefinition": (
        ".grc9v3_selector_validation",
        "GRC9V3SelectorDefinition",
    ),
    "GRC9V3SelectorResult": (
        ".grc9v3_selector_validation",
        "GRC9V3SelectorResult",
    ),
    "GRC9V3SelectorValidationSession": (
        ".grc9v3_selector_validation",
        "GRC9V3SelectorValidationSession",
    ),
    "run_grc9v3_selector_validation": (
        ".grc9v3_selector_validation",
        "run_grc9v3_selector_validation",
    ),
    "GRC9V3_VISUAL_REVIEW_VERSION": (
        ".grc9v3_visual_review",
        "GRC9V3_VISUAL_REVIEW_VERSION",
    ),
    "GRC9V3CheckpointLink": (".grc9v3_visual_review", "GRC9V3CheckpointLink"),
    "GRC9V3MotifVisualRecord": (
        ".grc9v3_visual_review",
        "GRC9V3MotifVisualRecord",
    ),
    "GRC9V3SkippedVisualRecord": (
        ".grc9v3_visual_review",
        "GRC9V3SkippedVisualRecord",
    ),
    "GRC9V3VisualReviewSession": (
        ".grc9v3_visual_review",
        "GRC9V3VisualReviewSession",
    ),
    "run_grc9v3_visual_review": (
        ".grc9v3_visual_review",
        "run_grc9v3_visual_review",
    ),
    "GRC9V3_HESSIAN_COMPARATOR_REVIEW_VERSION": (
        ".grc9v3_hessian_comparator_review",
        "GRC9V3_HESSIAN_COMPARATOR_REVIEW_VERSION",
    ),
    "GRC9V3HessianComparatorReviewSession": (
        ".grc9v3_hessian_comparator_review",
        "GRC9V3HessianComparatorReviewSession",
    ),
    "GRC9V3HessianLaneReview": (
        ".grc9v3_hessian_comparator_review",
        "GRC9V3HessianLaneReview",
    ),
    "GRC9V3HessianPairReview": (
        ".grc9v3_hessian_comparator_review",
        "GRC9V3HessianPairReview",
    ),
    "run_grc9v3_hessian_comparator_review": (
        ".grc9v3_hessian_comparator_review",
        "run_grc9v3_hessian_comparator_review",
    ),
    "GRC9V3_REVIEWED_MOTIF_CATALOG_VERSION": (
        ".grc9v3_reviewed_motif_catalog",
        "GRC9V3_REVIEWED_MOTIF_CATALOG_VERSION",
    ),
    "GRC9V3ReviewHistoryEntry": (
        ".grc9v3_reviewed_motif_catalog",
        "GRC9V3ReviewHistoryEntry",
    ),
    "GRC9V3ReviewedMotifCatalogSession": (
        ".grc9v3_reviewed_motif_catalog",
        "GRC9V3ReviewedMotifCatalogSession",
    ),
    "GRC9V3ReviewedMotifRecord": (
        ".grc9v3_reviewed_motif_catalog",
        "GRC9V3ReviewedMotifRecord",
    ),
    "run_grc9v3_reviewed_motif_catalog": (
        ".grc9v3_reviewed_motif_catalog",
        "run_grc9v3_reviewed_motif_catalog",
    ),
    "GRC9V3_CATALOG_BREADTH_EXPANSION_VERSION": (
        ".grc9v3_catalog_breadth_expansion",
        "GRC9V3_CATALOG_BREADTH_EXPANSION_VERSION",
    ),
    "GRC9V3CatalogBreadthExpansionSession": (
        ".grc9v3_catalog_breadth_expansion",
        "GRC9V3CatalogBreadthExpansionSession",
    ),
    "run_grc9v3_catalog_breadth_expansion": (
        ".grc9v3_catalog_breadth_expansion",
        "run_grc9v3_catalog_breadth_expansion",
    ),
    "GRC9V3_SOURCE_HANDOFF_VERSION": (
        ".grc9v3_source_handoff",
        "GRC9V3_SOURCE_HANDOFF_VERSION",
    ),
    "GRC9V3SourceHandoffSession": (
        ".grc9v3_source_handoff",
        "GRC9V3SourceHandoffSession",
    ),
    "run_grc9v3_source_handoff": (
        ".grc9v3_source_handoff",
        "run_grc9v3_source_handoff",
    ),
}


def __getattr__(name: str) -> object:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = _LAZY_EXPORTS[name]
    value = getattr(import_module(module_name, __name__), attribute_name)
    globals()[name] = value
    return value
